#!/usr/bin/bash
# darch initcpio install hook
# This determines what gets included in the initramfs

build() {
    # Add the runtime hook
    add_runscript

    # Add required binaries
    add_binary mount
    add_binary umount
    add_binary mkdir
    add_binary ln
    add_binary chmod
    add_binary sed
    add_binary cat
    add_binary sleep

    # Add btrfs support
    add_binary btrfs
    add_module btrfs

    # Add block device support
    add_module sd_mod
    add_module ahci
}

help() {
    cat <<HELPEOF
This hook sets up the darch (arch-atomic) root filesystem:
- Creates tmpfs root
- Mounts btrfs subvolumes (@images, @var, @home)
- Sets up symlinks to the current generation
HELPEOF
}

# vim: set ft=sh ts=4 sw=4 et:
